# Generated by Django 3.2.6 on 2021-09-07 11:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='List',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cardsoflist', to='api.list'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='Card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentsofcards', to='api.card'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignedcards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='list',
            name='Project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listsassociated', to='api.project'),
        ),
    ]
