# Generated by Django 3.2.6 on 2021-08-30 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='card_name',
            new_name='Card_name',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='list',
            new_name='List',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='card',
            new_name='Card',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='comment',
            new_name='Comment',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='User',
        ),
        migrations.RenameField(
            model_name='list',
            old_name='list_name',
            new_name='List_name',
        ),
        migrations.RenameField(
            model_name='list',
            old_name='project',
            new_name='Project',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='project_name',
            new_name='Project_name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_name',
            new_name='User_name',
        ),
        migrations.AlterField(
            model_name='card',
            name='assigned',
            field=models.ManyToManyField(to='api.User'),
        ),
        migrations.AlterField(
            model_name='project',
            name='admins',
            field=models.ManyToManyField(related_name='admins_Project', to='api.User'),
        ),
        migrations.AlterField(
            model_name='project',
            name='members',
            field=models.ManyToManyField(related_name='member', to='api.User'),
        ),
    ]
