# Generated by Django 3.2.6 on 2021-09-02 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210830_1115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='token',
        ),
        migrations.AlterField(
            model_name='card',
            name='assigned',
            field=models.ManyToManyField(to='api.User'),
        ),
        migrations.AlterField(
            model_name='project',
            name='admins',
            field=models.ManyToManyField(related_name='admins_Project', to='api.User'),
        ),
        migrations.AlterField(
            model_name='project',
            name='members',
            field=models.ManyToManyField(related_name='member', to='api.User'),
        ),
    ]
