# Generated by Django 3.2.6 on 2021-09-07 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile',
            field=models.FileField(max_length=254, null=True, upload_to=None),
        ),
    ]
